### PR TITLE
Update grpc dependency to ^1.1.1

### LINKED ISSUE #1: installation fails with latest stable version of Node
It looks like this is due to grpcli depending on an old version of grpc, which is not compatible with Node 7. If the grpc dependency is updated to 1.1.1, it fixes this issue.
ref: https://github.com/grpc/grpc/issues/8495#issuecomment-277046783

### PR DESCRIPTION
**Pull request by jab**
Fixes compatibility with latest major version of Node (7).
Ref: https://github.com/grpc/grpc/issues/8495#issuecomment-277046783
Closes #1.

### CODE REVIEW

**Comment by nathangoulding** [comment]
Thanks @jab!

**Comment by jab** [comment]
Thanks @nathangoulding, appreciate the quick merge! Would this be a convenient time to make a new release with this fix? I can work around it with yarn in the meantime, but maybe other users will have more trouble.

**Comment by nathangoulding** [comment]
@jab Just released 0.7.5. Thanks!

**Comment by jab** [comment]
Thank you @nathangoulding!

**Pull request merged**
